project:
  type: website
  execute-dir: project
  # output-dir: _site


website:
  title: "advanced BI"          # ← 변경
  description: "융합형 의사과학자 양성 사업"           # ← 변경
  navbar:
    logo: images/logo.jpg
    favicon: assets/img/logo.ico
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/kkonoo/advanced_BI_for_MD_PhD_KNUmed/

  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "1. Intro"
        contents:
          - chapters/part1/w1_intro.qmd
      - section: "2. Genomics"
        contents:
          - chapters/part2/w2_gwas.qmd
      - section: "3. Omics"
        contents:
          - chapters/part3/w4_epigenomics_methylation.qmd
      - section: "4. Multi-Omics"
        contents:
          - chapters/part4/w11_multiomics.qmd
      - section: "5. Capstone"
        contents:
          - chapters/part5/w13_visualization.qmd

  page-footer:
    left: "Copyright 2026, Eunji"


format:
  html:
    theme:
      light: cosmo
    css: assets/html.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    toc-float: true
    page-layout: full

    code-fold: false  
    code-copy: true
    highlight-style: github 

    number-sections: false
    smooth-scroll: true

    grid:                       
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 280px # toc

    # AI 채팅 위젯 전역 설정
    include-after-body: assets/ai-chat-init.html

  revealjs:
    css: assets/revealjs.css    # 슬라이드용
    scrollable: true


execute:
  freeze: auto          # 코드 실행 결과 캐시 (빠른 빌드)
  echo: true
  eval: false
  warning: false
  message: false

